"""Setup completion helpers — config writing, CLAUDE.md generation, hooks."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from loguru import logger

from backend.codos_models.settings import CODOS_CONFIG_DIR, CONFIG_FILE, PATHS_FILE
from backend.codos_utils.entity import get_entity_id
from backend.codos_utils.secrets import get_secrets_backend
from backend.codos_utils.system import get_system_name, get_system_timezone


def write_paths_json(codos_path: Path, vault_path: Path) -> None:
    """Write ``~/.codos/paths.json`` with the given paths."""
    paths_data = {
        "codos_path": str(codos_path),
        "vault_path": str(vault_path),
        "timezone": get_system_timezone(),
        "created_at": datetime.utcnow().isoformat(),
    }
    with open(PATHS_FILE, "w") as f:
        json.dump(paths_data, f, indent=2)


def copy_env_sh(codos_path: Path) -> None:
    """Copy ``env.sh`` from the repo to ``~/.codos/env.sh``."""
    env_sh_dest = CODOS_CONFIG_DIR / "env.sh"
    env_source = codos_path / "env.sh"
    if not env_source.exists():
        env_source = codos_path / "dev" / "Ops" / "env.sh"
    if env_source.exists():
        if env_sh_dest.is_symlink() or env_sh_dest.exists():
            env_sh_dest.unlink()
        env_sh_dest.write_text(env_source.read_text())
        env_sh_dest.chmod(0o755)


def seed_config_json(entity_id: str | None = None, user_name: str | None = None) -> None:
    """Merge entity and user info into ``~/.codos/config.json``."""
    if entity_id is None:
        entity_id = get_entity_id()
    if user_name is None:
        user_name = get_system_name()

    existing_config: dict = {}
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE) as f:
                existing_config = json.load(f)
        except (OSError, json.JSONDecodeError):
            pass

    existing_config.update(
        {
            "entityId": entity_id,
            "userName": user_name,
            "createdAt": existing_config.get("createdAt", datetime.utcnow().isoformat()),
        }
    )

    with open(CONFIG_FILE, "w") as f:
        json.dump(existing_config, f, indent=2)


def generate_vault_claude_md(vault_path: str, codos_path: str) -> None:
    """Write the thin redirect ``CLAUDE.md`` into the vault root."""
    vault_claude_md = Path(vault_path) / "CLAUDE.md"
    vault_claude_md_content = f"""# Atlas — Vault Context Directory

> This is the Atlas Vault. Full system instructions live in the Codos codebase.

Read `{codos_path}/CLAUDE.md` for complete Atlas instructions.

**Path adjustment:** When that file references `Vault/...` paths, they are relative to
this directory. Drop the `Vault/` prefix. Example:
- `Vault/Core Memory/About me.md` → `Core Memory/About me.md`
- `Vault/3 - Todos/{{today}}.md` → `3 - Todos/{{today}}.md`

---

*Generated by Codos Setup on {datetime.utcnow().strftime("%Y-%m-%d")}*
"""
    with open(vault_claude_md, "w") as f:
        f.write(vault_claude_md_content)


def migrate_global_claude_md() -> None:
    """Back up and remove global ``~/.claude/CLAUDE.md`` if it contains Atlas/Codos content."""
    global_claude_md = Path.home() / ".claude" / "CLAUDE.md"
    if global_claude_md.exists():
        try:
            content = global_claude_md.read_text()
            if "Atlas" in content or "DKOS" in content or "Codos" in content:
                backup = global_claude_md.with_suffix(".md.bak")
                global_claude_md.rename(backup)
                logger.info(f"Migrated global CLAUDE.md to {backup} (no longer needed)")
        except Exception:
            pass


def setup_hooks(codos_path: str) -> bool:
    """Make hook scripts executable. Returns True if hooks were found."""
    hooks_dir = Path(codos_path) / "backend" / "codos_services" / "gateway" / "hooks"
    if not hooks_dir.exists():
        return False
    for hook in hooks_dir.glob("*.sh"):
        hook.chmod(hook.stat().st_mode | 0o111)
    for hook in hooks_dir.glob("*.ts"):
        hook.chmod(hook.stat().st_mode | 0o111)
    return True


def save_api_keys(
    api_keys: object | None = None,
    telegram_bot_token: str | None = None,
    authorized_user_ids: str | None = None,
) -> list[str]:
    """Save API keys and bot credentials to the secrets backend.

    Returns list of key names that were written.
    """
    keys_saved: list[str] = []
    backend = get_secrets_backend()

    if api_keys is not None:
        key_mapping = {
            "ANTHROPIC_API_KEY": getattr(api_keys, "anthropic", None),
            "PARALLEL_API_KEY": getattr(api_keys, "parallel", None),
        }
        for env_key, value in key_mapping.items():
            if value:
                backend.set(env_key, value)
                keys_saved.append(env_key)

    if telegram_bot_token and authorized_user_ids:
        backend.set("TELEGRAM_BOT_TOKEN", telegram_bot_token)
        backend.set("AUTHORIZED_USER_IDS", authorized_user_ids.replace(" ", ""))
        keys_saved.extend(["TELEGRAM_BOT_TOKEN", "AUTHORIZED_USER_IDS"])

    return keys_saved
