#!/bin/bash
#
# Weekly Review Generator via Claude Code
#
# Gathers weekly context and invokes Claude Code to generate the review.
#
# Usage:
#   ./run-review-cc.sh
#

set -e

# Load environment (paths + API keys)
# shellcheck source=/dev/null
source ~/.codos/env.sh

SCRIPT_DIR="$CODOS_PATH/skills/Weekly Review"

# Calculate week info
YEAR=$(date +%Y)
WEEK=$(date +%V)
WEEK_PADDED=$(printf "%02d" "$WEEK")
REVIEW_PATH="$VAULT_PATH/0 - Weekly Reviews/${YEAR}-W${WEEK_PADDED}.md"

# Check if review already exists
if [ -f "$REVIEW_PATH" ]; then
    echo "Review already exists: $REVIEW_PATH"
    exit 0
fi

# Gather context
echo "Gathering weekly context..."
CONTEXT_FILE="/tmp/review-context-${YEAR}-W${WEEK_PADDED}.md"
cd "$SCRIPT_DIR"
VAULT_PATH="$VAULT_PATH" bun run gather-review-context.ts > "$CONTEXT_FILE"

echo "Context saved to: $CONTEXT_FILE"
echo "Invoking Claude Code to generate review..."

# Build the prompt - write to temp file to avoid heredoc quoting issues
PROMPT_FILE="/tmp/review-prompt-${YEAR}-W${WEEK_PADDED}.txt"
cat > "$PROMPT_FILE" << PROMPT_EOF
You are generating a Weekly Review. Read the context file at ${CONTEXT_FILE} and generate a comprehensive weekly review.

Follow this exact format:

# Weekly Review — Week ${WEEK} (DATE_RANGE, ${YEAR})

## a) Good Last Week
- [Specific wins with measurable outcomes]
- [Progress made on key goals]
- [Positive relationship developments]

## b) Bad Last Week
- [Hard truths - missed commitments, dropped balls]
- [Things that did not work as planned]
- [Time wasted or poor decisions]

## c) Key Learnings
- **[Learning title]** - [How to apply going forward]
- Focus on actionable insights, not abstract realizations

## d) Open Questions
- [Strategic questions without obvious answers]
- [Decisions that need more data]
- NOT action items - these are genuine uncertainties to sit with

## e) Progress Towards Goals

### Short-term Goals
| Goal | Status | Evidence |
|------|--------|----------|
| [Goal from Goals.md] | [On track / Behind / Blocked / Done] | [Specific evidence] |

### 2026 Goals
| Goal | This Week | Gap to Target |
|------|-----------|---------------|
| [Goal from Goals.md] | [What happened] | [How far from target] |

## Metrics
- Tasks: X/Y completed (Z%)
- Key meetings: [list with outcomes]
- Revenue progress: [if applicable]

---
Generated by Atlas

Rules:
1. Be brutally honest in section b). No sugar-coating failures.
2. Be specific - use names, numbers, quotes from the data.
3. Learnings must be actionable - "I learned X, so I will Y"
4. Open questions are NOT todos - these are genuine strategic uncertainties.
5. Goal progress must cite evidence - do not guess, use data from briefs/todos.
6. Max 5 items per section - prioritize the most significant.
7. Celebrate real wins - but only things that actually moved the needle.

Steps:
1. Read the context file at ${CONTEXT_FILE}
2. Analyze all the data from the week
3. Generate the review following the format above
4. Write the review to ${REVIEW_PATH}
PROMPT_EOF

PROMPT=$(cat "$PROMPT_FILE")

# Use subscription instead of API credits
# See: https://github.com/anthropics/claude-code/issues/3040
unset ANTHROPIC_API_KEY

# Invoke Claude Code
claude -p "$PROMPT" \
    --model opus \
    --allowedTools "Read,Write" \
    --permission-mode bypassPermissions

echo ""
echo "Review generated at: $REVIEW_PATH"
