#!/usr/bin/env python3
"""
Gemini Deep Research via API (Fallback)

Uses Gemini API for deep research when browser automation fails.
Requires GOOGLE_API_KEY in environment.

Note: API has per-query charges. Browser automation is preferred.
"""

import argparse
import os
import re
import sys
from datetime import datetime
from pathlib import Path

try:
    from google import genai
    from google.genai import types
except ImportError:
    print("Error: google-genai not installed. Run: pip3 install google-genai")
    sys.exit(1)


DEFAULT_OUTPUT_DIR = (
    Path(os.environ.get("VAULT_PATH", str(Path.home() / "Documents" / "Vault"))) / "2 - Projects" / "Research"
)


def slugify(text: str, max_length: int = 50) -> str:
    """Convert text to URL-friendly slug."""
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text[:max_length].strip("-")


def run_deep_research_api(
    topic: str,
    output_path: Path | None = None,
) -> str | None:
    """
    Run Gemini Deep Research via API.

    Args:
        topic: Research topic/prompt
        output_path: Where to save the result (auto-generated if None)

    Returns:
        Path to output file, or None if failed
    """

    # Check for API key — prefer env var, fall back to secrets backend
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        try:
            from backend.codos_utils.secrets import get_secrets_backend

            api_key = get_secrets_backend().get("GOOGLE_API_KEY")
        except ImportError:
            pass  # Script may run outside backend package context

    if not api_key:
        print("Error: GOOGLE_API_KEY not found")
        print("Set it via: python -m backend secrets set GOOGLE_API_KEY <key>")
        return None

    # Configure client
    client = genai.Client(api_key=api_key)

    # Generate output path if not provided
    if output_path is None:
        date_str = datetime.now().strftime("%Y-%m-%d")
        slug = slugify(topic)
        output_path = DEFAULT_OUTPUT_DIR / f"{date_str}-{slug}.md"

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("Starting Deep Research via API...")
    print(f"Topic: {topic}")
    print("This may take several minutes...")

    try:
        # Craft research prompt
        research_prompt = f"""You are a thorough research analyst. \
Conduct comprehensive research on the following topic.

Topic: {topic}

Instructions:
1. Provide a thorough, well-structured analysis
2. Include multiple perspectives and sources where relevant
3. Use clear headings and subheadings
4. Cite specific data, statistics, and examples
5. Include a summary of key findings
6. Note any limitations or areas needing further research

Format your response in clear Markdown with proper headings."""

        # Generate response using Gemini 2.0 Flash
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=research_prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=8192,
                temperature=0.7,
            ),
        )

        if not response.text:
            print("Error: Empty response from API")
            return None

        # Format output
        final_content = f"""# Research: {topic}

> Generated by Gemini API (Fallback)
> Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}
> Model: gemini-2.0-flash

---

{response.text}
"""

        # Save to file
        output_path.write_text(final_content, encoding="utf-8")
        print(f"\nResearch saved to: {output_path}")

        return str(output_path)

    except Exception as e:
        print(f"Error during API research: {e}")
        return None


def main():
    parser = argparse.ArgumentParser(description="Run Gemini Deep Research via API (fallback method)")
    parser.add_argument("topic", help="Research topic or prompt")
    parser.add_argument("-o", "--output", help="Output file path (default: auto-generated in Research folder)")

    args = parser.parse_args()

    output_path = Path(args.output) if args.output else None

    result = run_deep_research_api(
        topic=args.topic,
        output_path=output_path,
    )

    if result:
        print(f"\nSuccess! Research saved to:\n{result}")
        sys.exit(0)
    else:
        print("\nResearch failed. See errors above.")
        sys.exit(1)


if __name__ == "__main__":
    main()
